//! Cash flow forecasting.

use casiros_core::error::CalculationError;
use casiros_core::types::Dollar;
use chrono::NaiveDate;
use rust_decimal::Decimal;
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

/// The three standard cash flow statement categories.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub enum CashFlowCategory {
    /// Cash generated or consumed by core business operations.
    Operating,
    /// Cash used for or generated by long-term asset purchases/disposals.
    Investing,
    /// Cash from or paid to debt and equity holders.
    Financing,
}

/// A single expected (or actual) cash movement.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, ToSchema)]
pub struct CashFlowItem {
    /// Which cash flow statement category this item belongs to.
    pub category: CashFlowCategory,
    /// A human-readable description.
    pub description: String,
    /// The signed amount: positive is an inflow, negative is an outflow.
    #[schema(value_type = Decimal)]
    pub amount: Dollar,
    /// The date this cash movement is expected (or occurred).
    pub date: NaiveDate,
}

/// A forecast of future cash movements, used to project cash balances and
/// detect upcoming shortfalls before they happen.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CashForecast {
    items: Vec<CashFlowItem>,
}

impl CashForecast {
    /// Creates an empty forecast.
    ///
    /// # Examples
    ///
    /// ```
    /// use casiros_erp::treasury::cashflow::CashForecast;
    ///
    /// let forecast = CashForecast::new();
    /// assert!(forecast.items().is_empty());
    /// assert_eq!(forecast.items().len(), 0);
    /// ```
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    /// Adds an item to the forecast.
    ///
    /// # Examples
    ///
    /// ```
    /// use casiros_erp::treasury::cashflow::{CashFlowCategory, CashFlowItem, CashForecast};
    /// use chrono::NaiveDate;
    /// use rust_decimal_macros::dec;
    ///
    /// let mut forecast = CashForecast::new();
    /// forecast.add(CashFlowItem {
    ///     category: CashFlowCategory::Operating,
    ///     description: "Payroll".to_string(),
    ///     amount: dec!(-5000),
    ///     date: NaiveDate::from_ymd_opt(2026, 8, 20).unwrap(),
    /// });
    /// assert_eq!(forecast.items().len(), 1);
    /// assert_eq!(forecast.items()[0].amount, dec!(-5000));
    /// ```
    pub fn add(&mut self, item: CashFlowItem) {
        self.items.push(item);
    }

    /// Every item in the forecast, in insertion order.
    ///
    /// # Examples
    ///
    /// ```
    /// use casiros_erp::treasury::cashflow::{CashFlowCategory, CashFlowItem, CashForecast};
    /// use chrono::NaiveDate;
    /// use rust_decimal_macros::dec;
    ///
    /// let mut forecast = CashForecast::new();
    /// assert_eq!(forecast.items().len(), 0);
    /// forecast.add(CashFlowItem {
    ///     category: CashFlowCategory::Financing,
    ///     description: "Loan proceeds".to_string(),
    ///     amount: dec!(10000),
    ///     date: NaiveDate::from_ymd_opt(2026, 8, 1).unwrap(),
    /// });
    /// assert_eq!(forecast.items().len(), 1);
    /// ```
    #[must_use]
    pub fn items(&self) -> &[CashFlowItem] {
        &self.items
    }

    /// The net cash flow (inflows minus outflows) of items dated within
    /// `start..=end`, restricted to `category` if given.
    ///
    /// # Errors
    ///
    /// Returns [`CalculationError::Overflow`] if the running total overflows.
    ///
    /// # Examples
    ///
    /// ```
    /// use casiros_erp::treasury::cashflow::{CashFlowCategory, CashFlowItem, CashForecast};
    /// use chrono::NaiveDate;
    /// use rust_decimal_macros::dec;
    ///
    /// let mut forecast = CashForecast::new();
    /// forecast.add(CashFlowItem {
    ///     category: CashFlowCategory::Operating,
    ///     description: "Sales".to_string(),
    ///     amount: dec!(1000),
    ///     date: NaiveDate::from_ymd_opt(2026, 8, 10).unwrap(),
    /// });
    /// forecast.add(CashFlowItem {
    ///     category: CashFlowCategory::Investing,
    ///     description: "Equipment".to_string(),
    ///     amount: dec!(-400),
    ///     date: NaiveDate::from_ymd_opt(2026, 8, 15).unwrap(),
    /// });
    ///
    /// let start = NaiveDate::from_ymd_opt(2026, 8, 1).unwrap();
    /// let end = NaiveDate::from_ymd_opt(2026, 8, 31).unwrap();
    /// assert_eq!(forecast.net_cash_flow(start, end, None).unwrap(), dec!(600));
    /// assert_eq!(
    ///     forecast.net_cash_flow(start, end, Some(CashFlowCategory::Operating)).unwrap(),
    ///     dec!(1000)
    /// );
    /// ```
    pub fn net_cash_flow(
        &self,
        start: NaiveDate,
        end: NaiveDate,
        category: Option<CashFlowCategory>,
    ) -> Result<Dollar, CalculationError> {
        self.items
            .iter()
            .filter(|item| item.date >= start && item.date <= end)
            .filter(|item| category.is_none_or(|wanted| item.category == wanted))
            .try_fold(Decimal::ZERO, |total, item| total.checked_add(item.amount))
            .ok_or(CalculationError::Overflow {
                formula: "CashForecast::net_cash_flow",
            })
    }

    /// The projected cash balance as of `as_of`: `opening_balance` plus the
    /// net cash flow of every item dated on or before `as_of`.
    ///
    /// # Errors
    ///
    /// Returns [`CalculationError::Overflow`] if the running total overflows.
    ///
    /// # Examples
    ///
    /// ```
    /// use casiros_erp::treasury::cashflow::{CashFlowCategory, CashFlowItem, CashForecast};
    /// use chrono::NaiveDate;
    /// use rust_decimal_macros::dec;
    ///
    /// let mut forecast = CashForecast::new();
    /// forecast.add(CashFlowItem {
    ///     category: CashFlowCategory::Operating,
    ///     description: "Payroll".to_string(),
    ///     amount: dec!(-500),
    ///     date: NaiveDate::from_ymd_opt(2026, 8, 20).unwrap(),
    /// });
    ///
    /// let balance = forecast
    ///     .projected_balance(dec!(1000), NaiveDate::from_ymd_opt(2026, 8, 31).unwrap())
    ///     .unwrap();
    /// assert_eq!(balance, dec!(500));
    ///
    /// let before_any_items = forecast
    ///     .projected_balance(dec!(1000), NaiveDate::from_ymd_opt(2026, 8, 1).unwrap())
    ///     .unwrap();
    /// assert_eq!(before_any_items, dec!(1000));
    /// ```
    pub fn projected_balance(
        &self,
        opening_balance: Dollar,
        as_of: NaiveDate,
    ) -> Result<Dollar, CalculationError> {
        let Some(earliest) = self.items.iter().map(|item| item.date).min() else {
            return Ok(opening_balance);
        };
        let net = self.net_cash_flow(earliest, as_of, None)?;
        opening_balance
            .checked_add(net)
            .ok_or(CalculationError::Overflow {
                formula: "CashForecast::projected_balance",
            })
    }

    /// The earliest date on which the running balance (starting from
    /// `opening_balance`) would go negative, if any, walking the forecast's
    /// items in date order.
    ///
    /// # Errors
    ///
    /// Returns [`CalculationError::Overflow`] if a running total overflows.
    ///
    /// # Examples
    ///
    /// ```
    /// use casiros_erp::treasury::cashflow::{CashFlowCategory, CashFlowItem, CashForecast};
    /// use chrono::NaiveDate;
    /// use rust_decimal_macros::dec;
    ///
    /// let mut forecast = CashForecast::new();
    /// forecast.add(CashFlowItem {
    ///     category: CashFlowCategory::Operating,
    ///     description: "Big payment".to_string(),
    ///     amount: dec!(-1500),
    ///     date: NaiveDate::from_ymd_opt(2026, 8, 20).unwrap(),
    /// });
    ///
    /// let shortfall = forecast.first_shortfall_date(dec!(1000)).unwrap();
    /// assert_eq!(shortfall, Some(NaiveDate::from_ymd_opt(2026, 8, 20).unwrap()));
    ///
    /// let no_shortfall = forecast.first_shortfall_date(dec!(2000)).unwrap();
    /// assert_eq!(no_shortfall, None);
    /// ```
    pub fn first_shortfall_date(
        &self,
        opening_balance: Dollar,
    ) -> Result<Option<NaiveDate>, CalculationError> {
        let mut dated_items: Vec<&CashFlowItem> = self.items.iter().collect();
        dated_items.sort_by_key(|item| item.date);

        let mut running_balance = opening_balance;
        for item in dated_items {
            running_balance =
                running_balance
                    .checked_add(item.amount)
                    .ok_or(CalculationError::Overflow {
                        formula: "CashForecast::first_shortfall_date",
                    })?;
            if running_balance < Decimal::ZERO {
                return Ok(Some(item.date));
            }
        }
        Ok(None)
    }
}
