[package]
name = "casiros-dag"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
casiros-core = { path = "../core" }
petgraph = "0.6"
rust_decimal.workspace = true
serde = { workspace = true, features = ["derive"] }
thiserror.workspace = true

[dev-dependencies]
rust_decimal_macros.workspace = true
